export const EMAIL_DATA = "EMAIL_DATA";
export const FILTER_EMAIL = "FILTER_EMAIL";
export const EMAIL_SELECTED = "EMAIL_SELECTED";
export const EMAIL_DELETE = "EMAIL_DELETE";
export const EMAIL_SPAM = "EMAIL_SPAM";
export const EMAIL_MRKUNREAD = "EMAIL_MRKUNREAD";
export const GET_SEARCH_DATA = "GET_SEARCH_DATA";
